### ISSUE TITLE
ruby is missing shims

### ISSUE THREAD

**Issue by jdonaldson** [ScoopInstaller/Scoop#1139]
I can install python just fine, all of the commands wind up in my path as shims.  However, ruby doesn't seem to install the shims, and I can't launch it directly from the command.  

It's my first time trying scoop, let me know if you need more info or I'm doing something wrong.

**Comment by lukesampson** [comment]
The Ruby installer adds the bin directory to your PATH environment variable, rather than shimming executables. So you should be able to run `irb` right after installing.

You shouldn't have to restart your shell, but it might be worth a try to make sure the path is updated. 

If you're not having any luck, try looking at your PATH (e.g. $env:path or through system settings) and making sure the path to the ruby bin didn't get truncated or something like that.

**Comment by ironsand** [comment]
I had a same issue. Somehow the PATH environment variable was not added by the installer. I needed to add it myself.

The ruby version is  2.5.0-2, and I'm using Windows 10.

**Comment by 5paceToast** [comment]
Looking at the source for `env_add_path` (and `env_set`), the global settings seem to use a `$global` variable - is it possible it isn't passed in?

I notice specifically that (when using `scoop reset <app>`) my session PATH gets modified, it just resets for future sessions.
