### ISSUE TITLE
Scoop Commands

### ISSUE THREAD

**Issue by nueko** [ScoopInstaller/Scoop#1512]
Hi, Sorry this is not an issue, just want to write my thought about scoop commands.
1. I think it is better if scoop commands accept external args which will be passed to manifest scripts, eg: `scoop install unbound -x` or `scoop install unbound -- -x`
2. scoop commands will be better if it extendable, maybe with manifest `commands` property
3. add missing `scoop process` command

thanks.

**Comment by lukesampson** [comment]
I don't want to compromise the simplicity and understandability of installs too much to add extensibility. One of the main goals of Scoop is for it to be easy to write an install. Another one is for users to easily understand what an install is going to do. Allowing an install to do non-standard action based on arguments or manifest-defined commands is getting pretty far away from those goals. It requires the user to know a lot in advance, and gives them more ways to get it wrong.

What would the `scoop process` command do? If it's for starting a service that might be worth investigating. As I said in the PR, I don't think starting services in post_install is a good idea, because you can only do it that way once.

I have been opposed to Scoop starting services in the past because it doesn't seem like something an installer should do. It does seem to be something people want though. Ideally there would be something you can install with Scoop which could be used to start services in a standard way. However, if that doesn't exist, I wouldn't be opposed to adding a `scoop service start|stop|restart [app]` command to Scoop. Possibly it would make sense to add that as a `service` app that can be installed with Scoop.

**Comment by r15ch13** [comment]
Something like brew services? https://github.com/Homebrew/homebrew-services

**Comment by lukesampson** [comment]
I didn't know that was a thing — thanks. Yes, something like brew services.

It could just be a wrapper around `net start|stop` or `cmd /c sc`. The Scoop manifest could define a `service` property. Scoop would not register the service on install because that would require admin elevation. But when `sudo scoop service start [app]` is called it could look up the service in the install manifest, register the service and start it.

**Comment by nueko** [comment]
@r15ch13 yes something like brew services.
@lukesampson following snippet require no admin elevation.
```powershell
Start-Process -WorkingDirectory $psscriptroot -f unbound.exe  -a '-c service.conf' -WindowStyle Hidden
```

**Comment by safakgur** [comment]
Sorry for necromancing, but I believe external arguments would be a valuable feature.

It's not _essential_ for the majority since most software can be configured after installation. But there are some that install additional components that can't be "enabled" without reinstallation, some modify the registry (for stuff like adding context menu items to Explorer).

Even though these cases shouldn't exist in an [ideal world][1], we're not there just yet.

> It requires the user to know a lot in advance, and gives them more ways to get it wrong.

It shouldn't require anything from the users who are fine with the default options. And I believe it's reasonable to expect the ones who want an advanced installation to know what they're doing.

[1]: https://github.com/OneGet/oneget/wiki/8-Laws-of-Software-Installation#6-configuration-is-not-installation "8 Laws of Software Installation - Configuration Is Not Installation"

**Comment by niheaven** [comment]
In most case, scoop just extract every thing in the installer, and there is no need to configure the installer.

But if you really need custom installation, please consider making a new manifest with it and submit to [scoop/versions](https://github.com/scoopinstaller/versions).

**Comment by rashil2000** [comment]
#3736
