### ISSUE TITLE
Add ability to have a default architecture

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Scoop#1552]
Several programs have 64-bit versions, but the developers suggest that most users install the 32-bit version instead.

To solve this, what about adding something like:

````
    "architecture": {
        "32bit": {
            "default": true,
````
or
````
     "default": "32bit"
````
to our schemas?

Or maybe we want to indicate the quality of the architecture, and allow the user to not install "beta" software:

````
    "architecture": {
        "64bit": {
            "status": "beta",
````

And then add a config option to disallow installing "beta" software:

````
$ scoop config beta false
````

Let me know if a PR of either, or both, of these ideas would be considered. Thanks.

**Comment by lukesampson** [comment]
Is this for Apache and PHP? Can you list the programs that do this?

If the 64-bit version is beta while the 32-bit version is stable, aren't they two different versions?

The main bucket is for [release/stable versions only](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket), so beta 64-bit version can be left out of main bucket manifest, and a separate manifest added to the [versions](https://github.com/scoopinstaller/versions) bucket.

**Comment by ratatoeey** [comment]
this is somewhat related. 
instead of `scoop install -a 32bit` what about letting the user set the preferred architecture for all scoop apps in a configuration file. I expect scoop has a configuration file in the user's directory.

if no app is available the same message is displayed, which tells user that only 64-bit version is available. 

before, a reecent change in scoop. if you opened 64-bit powershell, the preferred architecture would be 64-bit and vice-versa(for 32bit). That was nice and intuitive. This addition would restore the previous function, but also be explicit and not dependent on the 32/64 bit-ness of powershell.

This should be simple to do. I don't plan on doing it due to multiple reasons.

----

coming back to this issue, if you want to implement it in scoop manifests, instead of default of preferred, maybe `developer-recommended` would be a better name for the actual field. as it would be less confusing.

And go much better with the user preferred architecture, if that gets implemented.
----

regards ratatoeey

**Comment by DrVektor** [comment]
i am trying to install foobar2000 64bit with scoop. But scoop appears like installing x64 but after i testing to look about section typing x86. i tried to installing "-a" option by "64bit" didnt change anything.

**Comment by HUMORCE** [comment]
> i am trying to install foobar2000 64bit with scoop. But scoop appears like installing x64 but after i testing to look about section typing x86. i tried to installing "-a" option by "64bit" didnt change anything. Scoop installing foobar2000 x86 but recommands encoder, i even installing encoder scoop gives message me encoder is x64. How does work x64 bit encoder with x86 foobar2000 player. What kind of confliction is this?

`extras/foobar2000` currently provides 32bit for all architectures, because it does not have corresponding download links for the architectures. That means it needs to be updated/improved, please create related issue in [extras bucket](https://github.com/ScoopInstaller/Extras).
