### ISSUE TITLE
How to switch nodejs version?

### ISSUE THREAD

**Issue by Garfield550** [ScoopInstaller/Scoop#1577]
I installed nodejs and nodejs-lts, I want switch Node.js LTS version to Node.js latest.
How to do it? Thanks!

```PowerShell
PS C:\Users\garfi> node -v
v6.11.0
PS C:\Users\garfi> scoop list
Installed apps:

  7zip (16.04) *global*
  nodejs (8.1.3) *global*
  nodejs-lts (6.11.0) *global*
  sudo (0.2017.03.24)
  yarn (0.27.5)

PS C:\Users\garfi> sudo scoop reset nodejs
'nodejs ()' isn't installed
```

**Comment by lukesampson** [comment]
`reset` isn't implemented for globally installed apps, so currently you'd have to reinstall these 2 Node.js versions without `--global` if you want to be able switch between them.

If you need global installs, currently you will need to reinstall `nodejs` (with`sudo scoop uninstall nodejs -g; sudo scoop install nodejs -g`) to use it again. So if you need to switch frequently it might work better to use `nvm` or non-global installs.

I'm marking this as a bug because we need to either implement global resets or give better feedback in the interface.
