### ISSUE TITLE
Handle install failures better

### ISSUE THREAD

**Issue by king6cong** [ScoopInstaller/Scoop#1864]
I often encounter this 
```
scoop install somepkg
# somepkg install failed previously. Please uninstall it and try again
scoop uninstall somepkg
scoop install somepkg
```
It makes me stop from time to time to handle this.
Maybe something like `reinstall` or `auto detect last failure and auto execute uninstall & install` is better?

**Comment by klauern** [comment]
I was just going to post the same thing.  Glad I looked up the existing issues.

For me, the issue is related to my corporate proxy blocking certain kinds of downloads unless I get them approved.  I can run `scoop update *`, but then when I find what failed, I have to `scoop uninstall` and `scoop install`, all while having lost the current working version.

It would be nice in my case to have the download complete (or fail) before uninstalling the old version.  If the install fails, it leaves my app completely uninstalled and not working until I get it fixed, which is mostly out of my hands.

**Comment by gmcouto** [comment]
this is so necessary.

**Comment by r15ch13** [comment]
@gmcouto yes, but look at this mess [install.ps1](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1) 😭

**Comment by rashil2000** [comment]
Fixed
