### ISSUE TITLE
Alert user if extract fails due to path length, and LongPathsEnabled != 1

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Scoop#2204]
Per https://github.com/lukesampson/scoop-extras/issues/889#issuecomment-381621827 , let’s add a check to https://github.com/lukesampson/scoop/blob/master/libexec/scoop-checkup.ps1 that we are under Windows 10 Version 1607, or later, and if LongPathsEnabled in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem is not set to 1, alert the user.

**Comment by se35710** [comment]
Duplicate of  #1523?

**Comment by rasa** [comment]
@se35710 They are certainly related.

**Comment by jfastnacht** [comment]
While the LongPathsEnabled check was implemented it still lacks the checkup for Windows 10 v1607, since I came across this problem on Windows 8.1 Pro.

The release ID needed should be available with:

`Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -ErrorAction SilentlyContinue -Name 'ReleaseId'`

This path is not available on Windows 8.1.
