### ISSUE TITLE
Permanent name for the real folder with the application

### ISSUE THREAD

**Issue by ustsv** [ScoopInstaller/Scoop#2365]
Now the structure of the folder with the application consists of versions of folders and symlink current. And shim points to the "current" symlink. But, in Win7, the firewall and antivirus see the application launching from the real path. For example: C:\ProgramData\scoop\apps\firefox\61.0\firefox.exe C:\ProgramData\scoop\apps\firefox\61.0.1\firefox .exe Accordingly, all the rules configured for the previous version are not visible to the new one. Is it possible to have a permanent name for the real folder with the application? Yes, I understand that the existing system allows you to avoid updating errors when working.

**Comment by rasa** [comment]
The only way I think of to make this work is instead of `scoop update app` doing:
1. install in `scoop/apps/1.1`
2. symlink `scoop/apps/current` to `scoop/apps/1.1`

it does:

1. copy `scoop/apps/current` to `scoop/apps/1.0`
2. install in `scoop/apps/current`
The latter may prove helpful when installing using an installer, as the installation/upgrade directory will always be the `current` folder.

Of course, switching from 1.1 to 1.0, would then require:
1. copy `scoop/apps/current` to `scoop/apps/1.1`
2. copy `scoop/apps/1.0` to `scoop/apps/current`

All the while persisting the `persist` folders.

Or is there a better way?

**Comment by pukkandan** [comment]
I have a similar requirement and this is the only issue I found on the matter. @rasa Could you explain why this was closed?
