### ISSUE TITLE
Question: apt-cyg

### ISSUE THREAD

**Issue by devilock76** [ScoopInstaller/Scoop#2688]
I am new to scoop. Mostly when on windows use WSL for linux like things, but in checking out scoop I decided to use it to also easily check out cygwin. I installed cygwin for my user only and apt-cyg is not available in the installed package. How does one enable apt-cyg for a user based cygwin install via scoop. The instructions I read for cygwin on the topic do not relate to this type of install. Excuse me if this is a dumb question, or not the place.

**Comment by Ash258** [comment]
Apt-cyq is not bundled with cygwin.
If you want to use it. It need to be added to scoop. I found only this [repository](https://github.com/transcode-open/apt-cyg), which is pretty old, so don't know if you are talking about this.

**Comment by matthewjberger** [comment]
I had the packages 'lynx' and 'wget' install by default in the cygwin manifest a few years ago so that people could install apt-cyg and other tools like that, but it looks like those packages were removed from the manifest here:

https://github.com/lukesampson/scoop/commit/44441c557d921f886503a3ccc8536f2464215dde?diff=unified#diff-746e2cad39291d6d1bcb57e3dc9d56a6L41

**Comment by E3V3A** [comment]
For `apt-cyg` you have to use [THIS](https://github.com/kou1okada/apt-cyg) version. The Transcode one is dead since a long time ago. apt-cyg as of today works great and is just a bash shell script in your PATH. 
Of course you need to already have a basic Cygwin installation. That said, it should be trivial to make Cygwin installed using scoop. 

However, I'm not sure how compatible scoop is with Cygwin, since it tries to install many similarly named tools. (I'm opening separate issue for that.)

**Comment by nitrocode** [comment]
I did notice that my apt-cyg packages were installed in this directory which is not in my path. 

```
/cygdrive/c/Users/user/scoop/persist/cygwin/root/usr/bin/
```

I don't understand why `apt-cyg` does not install it directly in `/usr/bin` or `/usr/local/bin` directories. Unsure if that is an apt-cyg issue or a scoop formula json issue.

I followed these steps and were able to get it to work correctly.

1. `scoop install cygwin`
1. Manually install wget, ca-certificates, and gnupg using cygwin-setup.exe
1. Using the fork suggested by @E3V3A, install `apt-cyg`
    ```
    git clone https://github.com/kou1okada/apt-cyg.git
    ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
    ```
1. Install `vim`
    ```
    apt-cyg install vim
    ```
1. Verify that cygwin cannot find vim
    ```
    which vim
    ```
1. Add the following to your `~/.bashrc` using `vi` or whatever editor
    ```
    PATH=/cygdrive/c/Users/user/scoop/persist/cygwin/root/usr/bin/:$PATH
    ```
1. Reload your shell or `source ~/.bashrc`
1. Verify that cygwin can now find vim
    ```
    which vim
    ```
