### ISSUE TITLE
Please avoid "reset default software/app"

### ISSUE THREAD

**Issue by n00d1e5** [ScoopInstaller/Scoop#3379]
As we know, some software like chromium and Atom **always has new version**.

In that case, I just update them and **cleanup the old version**.

But every time I done that, I **need to re-set up the default app**.

For example:

Once I update the text editor Atom (which is the default app for all text-like files) and cleanup it.

And then, I want to open a python file or text file, system will ask me to choose the software to open that.

**Comment by niheaven** [comment]
ref: https://github.com/lukesampson/scoop/issues/3271

I think this is due to Windows always pick ACTUAL execution file...

**Comment by n00d1e5** [comment]
I think now you are using the shortcut which is the symbolic link.
Do you think the hard link will solve the problem?

(I do not know so much about windows, if it's wrong, please excuse...)

**Comment by niheaven** [comment]
That is, scoop install apps in, e.g., `$SCOOP\apps\xxx\1.3.4`, and make a Junction in `$SCOOP\apps\xxx\current`, and all shortcuts and shims is target to later `current` dir. Since when update, the versioned dir is, e.g., `apps\xxx\1.3.5`, and `current` dir is the same. But Windows's default app is pointed to versioned dir which is deleted (by cleanup), so that's what you see now...

**Comment by n00d1e5** [comment]
I see.
Maybe an idea is the command update will do the following jobs:
- current version in folder $SCOOP\apps\xxx\ (no more version sub-folder)
- update download the latest version to $SCOOP\apps\xxx\tmp\
- copy all file to software file: copy $SCOOP\apps\xxx\tmp\* $SCOOP\apps\xxx\ /y
- rm the download files in $SCOOP\apps\xxx\tmp\

But this depends on Windows's default app is pointed by the path or others.

If the user do "Update", it means he/she wants the newer version. I do not know why scoop keep all the old version. In the special case. if user wants to collect, you could create a new command like $scoop install [app_name] -v 1.2.1. By doing this, scoop could create the folder like now, which is $SCOOP\apps\xxx\1.2.1

**Comment by AndrewSav** [comment]
>I think this is due to Windows always pick ACTUAL execution file

I think this is a problem specific to atom. It goes like this:

- scoop [shims](https://github.com/lukesampson/scoop-extras/blob/master/bucket/atom.json#L18) atom.cmd
- atom.cmd invokes `nodejs.exe atom.js`
- atom.js has [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths)(__dirname, '..', '..', 'atom.exe'); which resolves junctions.
And this is how you end up with the wrong path which has version in it instead of `current`

If you make a habit starting atom from the shortcut that scoop creates you will get the `current` one and that should work as expected. If you insist on starting that from command line... well either scoop can provide a different shim for the .exe instead of .cmd, or ask atom team to fix `atom,js` ;)
