### ISSUE TITLE
More challenge when uninstall scoop

### ISSUE THREAD

**Issue by Cologler** [ScoopInstaller/Scoop#3542]
Try to uninstall scoop require the user to input a random (or complex) string instead of a simple `Y`.

**Comment by kroppt** [comment]
Would this be to prevent someone from deleting your scoop or from accidentally doing so?
A script could easily parse the required input.

**Comment by Cologler** [comment]
Some people (like me) won't read warning messages and direct type `Y`.

**Comment by kroppt** [comment]
Other apps do not ask for any input to do the uninstall, so I think the y/n accomplishes this for uninstalling `scoop`. In this, case there is also a warning message.

However, I think that this addition would be good, because `scoop` is simple enough for knuckle heads to use (not saying that OP is one). Someone who is not a native-English speaker would also benefit from an extra check.

It is a known phenomenon that when a tool is easy to use, the average skill of the users actually lowers as more people start using it.

If this were added, there should be a flag for skipping the query, so that it can be used more easily in scripts.
