### ISSUE TITLE
Scoop is not in PATH of new shells

### ISSUE THREAD

**Issue by thejohnfreeman** [ScoopInstaller/Scoop#3551]
Scoop installs itself and adds itself to the `PATH` for that shell, but if I exit that shell and start a new one, it no longer appears on the `PATH`. Is there a registry setting or initialization file that needs to be changed? I'm coming from Linux and unfamiliar with the conventions on Windows.

**Comment by Ash258** [comment]
It is adding to path permanently for all sessions.

https://github.com/lukesampson/scoop/blob/b9b48182b4d921aa92e9b3e53ab2d2c376d467d7/lib/core.ps1#L622-L623

https://github.com/lukesampson/scoop/blob/b9b48182b4d921aa92e9b3e53ab2d2c376d467d7/lib/core.ps1#L459-L463

There is possible you need to log out, log in or restart for Windows to catch up and propagate it into all layers.

**Comment by kroppt** [comment]
If you are installing scoop to your user, you will not need to log back in, but if it's global then I believe yes.

You can check your PATH variables by typing into start menu, "environment variables" and choosing either "... for your account" or "system ..." to ensure it was actually set.

**Comment by thejohnfreeman** [comment]
There is only one installation command for Scoop, as far as I can tell, `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`, and it only installs for the current user.

This was in a container, so no Start Menu. I checked path with `echo %PATH%`.

**Comment by S0methingWicked** [comment]
I'm having the same issue as original poster. I've tried installing scoop several times now. I can install if I run Powershell as admin, but the shims directory only shows up in the path if I run Powershell as admin. No sign of the shims directory in non-admin path. If I try to install scoop in non-admin Powershell, I get an error after main bucket is extracted, saying that "scoop" command is unrecognized. No sign of it in the path.

I'm assuming this may be something to do with how my company has set policies in our default image.

**Comment by rwv37** [comment]
I just had this issue, and resolved it:

(1) I installed Scoop using PowerShell, which I had running in a Windows Terminal tab.

(2) Scoop was working fine in the PowerShell instance that I had installed it with.

(3) At some point after having done what I wanted with Scoop, I closed that PowerShell instance.

(4) A couple days later, I wanted to use Scoop again, and opened up a new PowerShell instance in that same Windows Terminal instance. Scoop did *not* work.

(5) I verified that Scoop had installed its entries in my path environment variable.

(6) I opened up a *new* instance of Windows Terminal, and a new instance of PowerShell within that. Scoop worked fine there.

So I guess the issue (for me, at least) is that although Scoop added its path stuff both on my computer and in the PowerShell instance that I used to install it, the Windows Terminal instance that I was running that PowerShell instance in did *not* pick up that change. So I guess the new PowerShell instance got its environment stuff from the Windows Terminal instance, rather than from Windows itself.

**Comment by dfrisinghelli** [comment]
Solved with @rwv37's solution.

**Comment by maple3142** [comment]
Same with @rwv37 , reopening Windows Terminal fixes the problem

**Comment by rmdes** [comment]
Having a similar version of this issue, except, while scoop is on path, I can't get it working from any shell/env
