### ISSUE TITLE
Downloads are painfully slow

### ISSUE THREAD

**Issue by guptadd** [ScoopInstaller/Scoop#3665]
I have a 40Mbps connection. But when installing anything through Scoop, I get ~8Mbps download speed. How can I debug this?

**Comment by SonOfDiablo** [comment]
Are you trying to install anything in particular or is it everything that downloads with 8Mbps?
As far as I can see Scoop downloads from the provided urls in the manifest, so it could just be a limit on the providers side.

Have you tried just downloading the app(s) from the website(s) manually?

**Comment by guptadd** [comment]
@SonOfDiablo 
So actually it was even slower than the 8Mbps I had earlier specified. I downloaded balena Etcher normally through Firefox and got around ~3Mbps and the download seemed exactly as fast as scoop. But when I downloaded it through a download manager (Ninja Download Manager) I was getting ~20Mbps, and the download completed in seconds.

I believe Firefox only creates a single connection (i.e. does **NOT** download multiple parts simultaneously and then merge them afterwards). So, the limit is actually on the providers end on a single connection. But the download manager I used most likely creates around 6-8 connections simultaneously.

**Comment by SonOfDiablo** [comment]
Scoop can use aria2 for multi-connection download.
Check out how here: https://github.com/lukesampson/scoop#multi-connection-downloads-with-aria2

**Comment by guptadd** [comment]
@SonOfDiablo 
Yes, thank you very much, that works perfectly.

**Comment by maludwig** [comment]
It seems that there's an issue with the implementation of the progress bar for PowerShell's InvokeWebRequest, installing aria2 will fix it, but I needed to use this beforehand to get aria2 to download in time (disables the progress bar):

```
$ProgressPreference = 'SilentlyContinue'
scoop install aria2
```

**Comment by codenoid** [comment]
hello, this is happen again, this should be done in second but already wait for 2 minute, my connection is normal

![image](https://github.com/ScoopInstaller/Scoop/assets/14269809/f3e3d1d5-a749-4d8d-8272-5f76cf3f8e4c)

**Comment by jenny923432** [comment]
I still see this with specific packages only, within the main bucket. aria2 downloaded at 11 MB/s. findutils, a 601 KB package, can't be installed at all because it goes at 200 - 1000 _bytes_ per second for 10 minutes before getting an unexpected EOF or 0 bytes. Holds true across multiple computers on separate Internet connections, there's just something about specific packages that seems to slow it to a sub-dialup crawl.

Can anyone else try installing findutils and seeing if they can reproduce it?

**Comment by romabysen** [comment]
I have the same problem with Calibre.
The `calibre` package is fast to download but `calibre-normal` is super slow. Both are downloading from the same site: `download.calibre-ebook.com`

**Comment by RaphaelTarita** [comment]
experiencing the same issues sporadically, currently with `php` updating to 8.3.14, which is a 30.8 MB download but it goes so slow that I couldn't get it to finish before getting a timeout.. it's not the first time I see such behaviour but it's the first time that I acutally cannot update because of the timeout. In the past, it seemed like these problems would go away over time, I don't know if it will be the same for `php`.
