### ISSUE TITLE
scoop update notification frontend bg app that lives in tray

### ISSUE THREAD

**Issue by filipworksdev** [ScoopInstaller/Scoop#3678]
Most package managers have some basic frontend application that  that runs in the background usually in the tray and regularly checks for updates, notifies the users if any update is available, and sometimes even provides a quick update functionality with the click of a button.

have tried to look for similar requests couldn't find any.

Please disregard if this feature has already been requested, if it already exists or something like this has already been discussed and rejected by devs.

**Comment by foosel** [comment]
I just started using scoop, barely created my own bucket, and until yesterday had never before written even a single line of Powershell.

Nevertheless, I tried my hand at this, and here is a very first version:

https://github.com/foosel/scoop-tray

Polls `scoop status` every 30min and extracts scoop and app update status from that. If there are new updates found for either scoop itself or any of the installed apps, the icon will turn orange and a notification will also be triggered. An update (`scoop update` and/or `scoop update *` as needed) can then be triggered via the context menu.

Seems to work right now, long term test will tell me more. Nevertheless I thought I'd share here since I was looking for something like this yesterday and came across this ticket.

**Comment by itsmeboy0** [comment]
I found this too: https://github.com/tech189/scoop-notifier

@tech189 any differences between your project and the one above?

**Comment by tech189** [comment]
My project is a Python script that generates a silent task in Task Scheduler, so it doesn't run in the background in the tray (like the project above) but is called as often as you specify, sending a notification when there are updates available. It's not finished however, I'd like to compile it with pyinstaller (if possible) so that it can be installed as a Scoop package! (at the moment you need to run it with `poetry`)

**Comment by sitiom** [comment]
[WingetUI](https://github.com/martinet101/WingetUI) (which also supports Scoop) has also recently implemented this (https://github.com/martinet101/WingetUI/issues/44).
