### ISSUE TITLE
Options to install without updating first

### ISSUE THREAD

**Issue by rikuben** [ScoopInstaller/Scoop#3739]
Recently I installed something that broke my git installation somehow. Git is installed via scoop. The git command becomes unresponsive and won't stop until I use Ctrl+C. When I try to reinstall git with scoop, scoop will try to update the buckets first, and so, it becomes unresponsive too. I end up just downloaded portable-git and unpacked it manually to the scoop app folder. It would be great if there's a way to force reinstall/install without the need to update first.

**Comment by CrendKing** [comment]
Also, I have scheduled task to periodically execute `scoop update` in the background. There is really not much to update whenever I install something. But because I include many 3rd-party buckets, I have to wait through all the "Update '<name>' bucket...". Please consider this.

**Comment by rasa** [comment]
I agree. Apt has an `apt update` which is separate from `apt-install` or `apt upgrade`. We could skip update, unless it's been over X seconds since the last update, and/or the user adds a `--update` option

**Comment by r15ch13** [comment]
Scoop only updates if the last update was 3h ago.
This enforced update was integrated to make sure every manifest file is still valid. (e.g. PHP moves everything to a different directory when a new version is released, so an outdated manifest file can't find the files anymore). `apt update` doesn't need to be run so often because the sources don't move or delete older versions, but we rely on the program provides download servers.

@CrendKing make sure your scheduled task runs as the same user so `lastupdate` in `%USERPROFILE%\.config\scoop\config.json` gets updated properly or run it more often.

**Comment by equinox** [comment]
How about making it configurable via a config option? Alternatively, if possible, another solution could be just updating the bucket the app is going to be installed from, rather than them all.

**Comment by CrendKing** [comment]
> Scoop only updates if the last update was 3h ago.

That explains. My task executes every 8 hours.

> `lastupdate` in `%USERPROFILE%\.config\scoop\config.json` gets updated properly or run it more often

So a possible hack is to create a PS alias that 1) "touch" the "lastupdate" field; 2) run `scoop install` as usual. Totally doable. Thanks.
