### ISSUE TITLE
Support creating files in manifest

### ISSUE THREAD

**Issue by JanPokorny** [ScoopInstaller/Scoop#3752]
There are many manifests that rely on install scripts to create files. The usual reason seems to be creating empty files in place of config files created only after program startup, that need to be persisted -- Scoop defaults to creating a folder when a file/folder in `persist` does not exist. There are countless examples of using [New-Item](https://github.com/lukesampson/scoop-extras/search?q=New-Item&unscoped_q=New-Item) and [Add-Content](https://github.com/lukesampson/scoop-extras/search?q=Add-Content&unscoped_q=Add-Content) for this purpose.

Another reason might be creating default config files, ie. forbidding auto-update (ex. [potplayer](https://github.com/lukesampson/scoop-extras/blob/74922a17fe23eea40ac582d0edce281fde86f35a/bucket/potplayer.json#L41) or [winscp](https://github.com/lukesampson/scoop-extras/blob/69709c2635ff94b484abf51c0a56d045b0873a46/bucket/winscp.json#L9)).

Another is creating custom launch scripts -- which currently need to be echoed from inside PowerShell, creating an escaping mess (ex. [sagemath-installer](https://github.com/lukesampson/scoop-extras/blob/master/bucket/sagemath-installer.json#L15)).

I think it would lead to cleaner and shorter manifests, if Scoop supported directly "dropping" files, without the need for the PowerShell pattern. The manifest would provide a map from file path (relative to $dir) to file content (either string or string array to be joined as lines, as is usual). Scoop would then create those files with such content during installation, unless file of that name already exists.

Example:

```js
{
  //...
  "create_files": {
    "config.ini": "",
    "subfolder/config2.ini": [
      "[Main]",
      "autoupdateEnabled = 0",
      "portableMode = 1"
    ]
  }
}
```

**Comment by Ash258** [comment]
#3212  #3587

**Comment by JanPokorny** [comment]
@Ash258 I seem to suck at searching through issues, and believe me I tried

**Comment by JanPokorny** [comment]
@Ash258 These seem to concern only the case for `persist` files, do I understand that correctly? Or will it also cover the cases of dropping a non-persisted config/script file? There are cases where persisting such file might be a bad idea, ie. when the dropped file needs to be changed in a new version.

**Comment by Ash258** [comment]
#3212 is just for persists.

And for general creation of files it is not good idea to keep it as manifest property in my opinion, as universal solution will not cover most use cases and you need to go into install blocks anyway.
Since lots of configurations have some default file you need to load it, change it, or do other stuff. If you will have easy `file` and `content` "map", then you will miss opportunity to configure line ending, encoding or there just need to be really advanced manifest property, which will cover all parameters of `new-item`, `set-content` and ideally with custom script again, which is non ergonomic and would be pain to maintain. Also it would have to be powershell compatible with scopes, variable resolution and context sharing.

With #3587 there could be added any type of helpers, which are widely used to keep maintaners sanity low with simple syntax (for example windows version check, administrator check or .Net framework, which were added few hours back). For example registry manipulation could go next.

Escaping hell is mainly caused due to json. But there is no problem to utilize other scoop core functions, which could help with it. I am not familiar with some really hardcore custom shim.

**Comment by JanPokorny** [comment]
@Ash258 I based the issue on going through manifests in the `extras` bucket (see the search links in the OP), and most seem to quite simply drop a file, either empty or a few lines long. This was not intended as a catch-all, but rather a one-size-fits-most solution for common manifest needs.

I have not been able to find a single manifest that would modify an existing config file (loading it, appending to it etc). Similarly, I haven't seen one that would require setting UNIX line endings or changing encoding (or, rather, even using non-ASCII characters in the default config in the first place). I don't deny that such manifest does/can exist, though, but it seems to be rather rare.

If there's a manifest that needs to do anything more complicated, PowerShell script is definitely more readable and accessible than a complicated custom JSON schema. The point of my proposal is to allow an alternative for simple (and common) cases, where using a simple file-content map is shorter and more readable than the default PowerShell pattern.

**Comment by rashil2000** [comment]
#3166
