### ISSUE TITLE
How to stop scoop from auto-updating buckets?

### ISSUE THREAD

**Issue by wuchangen** [ScoopInstaller/Scoop#3818]
tldr: title

I use a lot of buckets. It becomes tedious  that every time I use scoop to install software, it automatically starts to update buckets. Which takes quite a few minutes. So is there an option to set it off? I looked at the wiki and couldn't find it. Thank you.

**Comment by quantuumsnot** [comment]
Yeah, I'm also wondering why scoop must check AND update all buckets when it's faster to check only the installed apps. Most if not all have the same source URL from where the latest version can be downloaded (date/version comparison are enough). Then it's better to update only the .json for each app

**Comment by r15ch13** [comment]
`apt`, `pacman` and `brew` all work the same.
First, update the local package database and then update the programs.
In the case of these tools, you have to run the update manually (e.g. `apt update`), but Scoop enforces `scoop update` after 3 hours of the last run.
This ensures that hashes and versions are up-to-date because we don't have a history of packages or have any control over the download servers. It was implemented by me to reduce the number of issues opened for wrong hashes and non-existent download URLs because a user didn't run `scoop update` beforehand.

The slowness of the bucket update comes from `git pull`. I tried to make this a parallel task, but sadly couldn't get it to work.

**Comment by quantuumsnot** [comment]
Update only INSTALLED apps, why should we update all buckets instead of updating only manifests?

**Comment by r15ch13** [comment]
And what if you want to install a new program? Or search locally for it?

**Comment by quantuumsnot** [comment]
Then update the buckets one by one only if `scoop search yourapp` returns false, for each installed bucket, ie:
scoop searches in bucket 'main', finds nothing > update 'main'
v
scoop searches in bucket 'main', finds nothing but 'main' is updated
v
scoop searches in bucket 'extras', finds nothing > update 'extras'
v
scoop searches in bucket 'extras', finds yourapp ...

**Comment by ddavness** [comment]
>`apt`, `pacman` and `brew` all work the same.
First, update the local package database and then update the programs.

I don't think this was ever true - at least not automatically.
As far as I know you'd still be required to update stuff manually - `apt update`, `pacman -Sy`, etc.

**Comment by h404bi** [comment]
https://github.com/lukesampson/scoop/blob/11c42d782f8adb29fbe0d94daa5f121cdda935ab/libexec/scoop-install.ps1#L70-L72

change this to:

```powershell
if (is_scoop_outdated) { 
    warn "Scoop is outdated. Maybe you are installing an older version of apps."
}
```

or whatever.

**Comment by quantuumsnot** [comment]
In general versions of scoop maintained apps shouldn't have anything in common with scoop. Any version of any package system must have backwards compatibility, ie even the latest version of scoop should install each one of the 'old' app versions and any of the latest app version can be installed by the oldest version of scoop

**Comment by r15ch13** [comment]
@ddavness 
> I don't think this was ever true - at least not automatically.

You're right. You have to run `apt update` first.

@quantuumsnot 
Scoop can't install 'old' app versions in many cases.
Many developers don't provide older versions of their programs or the URL is always the same (without a version number in it).
Now you have an old manifest without the correct hash in your local outdated bucket and try to install the program. Scoop will report a hash mismatch and cancel. Many users would create a new ticket instead of running `scoop update` first. This was the case before the forced update was implemented.

Any other package system relies on an organized and consistent server structure.

Adding a config value to switch it off would be a solution, but it shouldn't be off by default.

**Comment by quantuumsnot** [comment]
I know that but also know that version numbers and storing them in the manifest should be mandatory. Often the newest version has and new bugs or incompatibilities with some systems

**Comment by wuchangen** [comment]
@h404bi 
That's what needed, thank you.

**Comment by pjeby** [comment]
Note for people finding this in future: you can now use `-u` or `--no-update-scoop` as an option to the install command (and a `-l` / `--local` option to the status command) to prevent bucket updates.  I defined aliases so I can use `scoop i` and `scoop s` to install or check status locally as follows:

```
scoop alias add i 'scoop install -u @args' "Install package without updating scoop"
scoop alias add s 'scoop status -l @args' "Show package status without updating scoop"
```

Hopefully this will be of use to others coming across this issue in future.

**Comment by TylerTemp** [comment]
> 

`brew` allows an env variable to disable this function, thus editing a profile file (or modify system env) can do it for all

`apt` allows editing config file to disable it once for all.

So, either a env, a config, or a global first-class command-line option would be appreciated.

for example, if an `--no-update-scoop` is to be global then we can alias `alias scoop=scoop --no-update-scoop` on cygwin, or wrap the original scoop bin file to a `scoop.bat` and give a higher priority in `PATH`.

Otherwise, this is just painful.

**Comment by gigberg** [comment]
> Note for people finding this in future: you can now use `-u` or `--no-update-scoop` as an option to the install command (and a `-l` / `--local` option to the status command) to prevent bucket updates. I defined aliases so I can use `scoop i` and `scoop s` to install or check status locally as follows:
> 
> ```
> scoop alias add i 'scoop install -u @args' "Install package without updating scoop"
> scoop alias add s 'scoop status -l @args' "Show package status without updating scoop"
> ```
> 
> Hopefully this will be of use to others coming across this issue in future.

thanks, i have found for this feature these years

**Comment by goyalyashpal** [comment]
* https://github.com/ScoopInstaller/Scoop/issues/5044

**Comment by gigberg** [comment]
`scoop update appname` will update scoop and bucktes every 3 hours: 
```powershell

# lib/core.ps1#L1166-L1176
function is_scoop_outdated() {
    $now = [System.DateTime]::Now
    try {
        $expireHour = (New-TimeSpan (get_config LAST_UPDATE) $now).TotalHours
        return ($expireHour -ge 3)
    } catch {
        # If not System.DateTime
        set_config LAST_UPDATE ($now.ToString('o')) | Out-Null
        return $true
    }
}
```
To someone who is looking for an option avoiding so frequent updating, especially with bad network, there is a feasible alias:
```powershell
scoop alias add update_ "scoop config last_update ([System.DateTime]::Now); scoop update @args" "Update package without updating scoop and buckets"
```
which generates a scoop-update.ps1 file in scoop\shims directory, then you could use scoop update_(with underline) to bypass buckets update step.

by the way, these are all other alias I have used for years:
```powershell
scoop alias add install_ "scoop install -u @args" "Install package without updating scoop"

scoop alias add update_ "scoop config last_update ([System.DateTime]::Now); scoop update @args" "Update package without updating scoop and buckets"

scoop alias add status_ "scoop status -l @args" "Show package status without updating scoop"

scoop alias add download_ "scoop download -u @args" "Download package to cache without updating scoop"


scoop alias add listof '$appname=$args[0]; scoop shim list | Where-Object {$appname -in ($_.Source + " " + $_.Alternatives).Split()}' 'list all shims of specific app'

```
