### ISSUE TITLE
Scoop failing to "shim" 7z.exe when installing 7zip.

### ISSUE THREAD

**Issue by Vexxlol** [ScoopInstaller/Scoop#3862]
Get's stuck on this. 
![image](https://user-images.githubusercontent.com/40529545/75225288-0a06a380-57f6-11ea-8daa-63f5a7cf46dc.png)

And if i hit enter i get this error. 
![image](https://user-images.githubusercontent.com/40529545/75225334-1ee33700-57f6-11ea-8f71-b3adfbb86673.png)

I need 7zip to install other programs :/

**Comment by archit9169** [comment]
install git. Update scoop buckets to get latest revision. and then try again

**Comment by davidfokkema** [comment]
I had a student with this exact problem. After quite a lot of digging in, we uncovered that `cmd.exe` was the culprit. The 'regular' command prompt could not be started from the Start menu (nothing happened) and `cmd` in a Powershell did nothing. Scoop uses `cmd.exe` to run the linking step and that failed silently. Hence, no `7z.exe` found. The reason was a corrupt Autorun registry key. You can try this: open Windows Powershell and run:
```powershell
PS> cmd /c echo hello world
```
That should print `hello world`. If it does not, try *without* the autorun scripts:
```powershell
PS> cmd /d /c echo hello world
```
(mind the `/d` flag). If that *does* work, check the contents of the following registry keys (use e.g. `regedit`):
```
HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
```
Edit the keys, or remove them completely.
