### ISSUE TITLE
Scoop reset does not invoke post install commands

### ISSUE THREAD

**Issue by archit9169** [ScoopInstaller/Scoop#3939]
When using the reset command in scoop, it does not invoke the post install commands for the app. It creates the shims, shortcuts, env and path but does not run the post install commands.

Eg: scoop install vcredist :- It install the vcredist, and gives uac prompt to install the installer.
scoop reset vcredist :- It does not gives uac prompt to install the installer.

Workaround :- I can use scoop update vcredist -f for the same. However i believe it should be implemented in reset command. Maybe as another flag -f or something to force the post install script execution.

**Comment by pfmoore** [comment]
Confirmed. I have [an app](https://github.com/pfmoore/scoop-enk/blob/master/bucket/cyg.json) that adds a set of binaries in its post-install script, based on a user config file.

Because of this issue, I cannoy use `scoop reset` when the user changes the config file.

Thanks @archit9169 for the workaround, it's not ideal but at least it does the job :-)

**Comment by rashil2000** [comment]
The post_install, pre_install, installer.script and uninstaller.script contains arbitrary PowerShell commands, running which is not the purpose of `scoop reset`. As mentioned in the workaround, if you need to execute any of those commands, force-update the app.
