### ISSUE TITLE
The Windows official package manger winget-cli has released, what should we do?

### ISSUE THREAD

**Issue by wenmin92** [ScoopInstaller/Scoop#3992]
[Windows Package Manager Preview | Windows Command Line](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/)

**Comment by linsui** [comment]
> We have already talked with a few of the well-known package manager teams. Chocolatey has a vibrant community with a massive collection of applications, and a rich history supporting both open source and enterprise customers. Scoop provides a convenient way to allow software to be installed without the UAC popups. Ninite keeps an eye on updates for all the apps it installed. There are many others like AppGet, Npackd and the PowerShell based OneGet package manager-manager.

I'm curious about what they talked. :joy:

Scoop is more portable and silent. Before there is a portable source for winget, Scoop is the best choice for me.

**Comment by zjgcjy** [comment]
I like the principle of scoop, that is portable and silent, as linsui mentioned above.

**Comment by NatoBoram** [comment]
Personally, I'm not after the "portability" of Scoop, as I'll never move it around from a computer to another. But I *do* love the self-containment aspect it brings.

Right now, WinGet is [struggling with Nightly support](https://github.com/microsoft/winget-pkgs/issues/278) that Scoop had since https://github.com/lukesampson/scoop/issues/181.

I might not end up using WinGet, but I decided to [contribute](https://github.com/microsoft/winget-pkgs/pull/332) because it's easier since they have an automated tool to help.

**Comment by gerardog** [comment]
We should add a Scoop manifest to WinGet Repo. So people can easily migrate to Scoop once they discover it's already years ahead.

**Comment by NatoBoram** [comment]
I think it would totally be possible to add a Scoop manifest that just runs `Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')`

**Comment by Naomi010Sentzke** [comment]
It does support appx and msix that Scoop does not. Eventually it will also let you install from the Store itself. I feel like both Scoop and Winget can co-exist.

**Comment by Restia666Ashdoll** [comment]
@Naomi010Sentzke That is if they implement everything in their roadmap by v1
https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md#v10-scenarios
There are many things Scoop does, that winget can never do. But if we consider UWP apps and Windows Store, the reverse can also be true(or stuffs like Visual Studio Community). If it matures I may use both.

**Comment by mxrss2** [comment]
I dont think there is anything to really do right now, just a wait and see approach. Someone brought up isnt this what OneGet was supposed to be? 

I am very confused, why are we even looking at installing apps and not looking at offering abilities for win containers to use some kind of isolated storage. It appears most apps are going online to offer the broadest compat level, but apps that still require access to a machine (for dependencies or for apps, or for vendors that refuse to modernize or cant). 

But here we are 20 years after package managers were considered cutting edge and the unwashed MS masses are parroting this is the "killer feature" for windows. I really think that this is bound for vapor ware. It might have integration, but like someone said this is just a solution in search of a problem. Maybe after 3 years and 5 versions it will be something that has to be considered what does the scoop community do, but its way to early to determine if this is some kind of Me Too project.

@lukesampson made a good package manager that embraces the "Do One Thing and Do it well philosophy".

**Comment by lukesampson** [comment]
Great points @mxrss2, @gerardog , @NatoBoram, @linsui and @Restia666Ashdoll.

This is mostly just speculation and I'm far from an attentive observer. Just throwing my 2 cents in.

Microsoft lately (Nadella era? I don't know) seems be going for buzz, trying to generate excitement and optimism about their platforms. But they don't seem to have any follow through. Products don't seem to go anywhere, there doesn't seem to be as much commitment to making things that are best in class any more. They throw things out to "the community" and hope that open source developers will finish their work for them. There are exceptions of course and a lot of people in MS that are pushing really hard. I would expect these are some of the smartest people in tech, but their management and corporate culture, and parasitic alignment with open source philosophy seem to be screwing them up. Programmers are not being given the support they need to develop projects to maturity and excellence, they are only incentivised to develop one flashy release candidate and make a bit of a splash at Build conferences. If you look at Demetrius Nelon's Linked in profile, he's been at MS 2 years and his primary achievement there (according to him) is "Delivering the Windows Package Manager Preview in time for //BUILD 2020". This isn't a personal attack on Mr Nelon, but I'm just noticing that maybe there is something going on here.

I think this is quite likely what will happen with WinGet. They won't get anywhere near the traction of Scoop or Chocolatey and the people working on it internally will get reassigned to the next sounds-good product. I think this would be a shame. But I also think it means that Scoop is just as necessary and useful as before.

I don't know if these rambling thoughts are helpful in any way, but I felt like I might be forgiven for indulging in some encouragement since I do very little around here these days. Maybe I'm totally off with this prediction. But Scoop is still the best in class in terms of functionality and aesthetic. We have the best people working on it, and the most buy-in from smart developers who care about how these things work. I'm very grateful to everyone who has contributed and made Scoop what it is today. I hope everyone can see that it's far from over for Scoop.

**Comment by Restia666Ashdoll** [comment]
I just view winget as something different. It uses data in yaml instead of scripts. Here is a manifest for notepads I made. After lots of modifications (and more by RandomLabs) I decided to go for the store version
https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/notepads-np.json
winget has "Installing from Store" on the top of their roadmap and already supports msix/appx.
Then there are issues like this
https://github.com/ScoopInstaller/Main/issues/924
I feel like PowerShell and Windows Terminal should not be used from Scoop if you use them primarily. Firefox does not retain data after updates. There is no Visual Studio Community Edition manifest etc. I love Scoop, but its not the solution to everything.
Like I said a lot of stuffs in Scoop can never be possible in winget. Like this new bucket.
https://github.com/TheRandomLabs/Scoop-Python

Thats why rather than hope that it fails, I would wait for v1. Ultimately Windows Terminal turned out to be great. Thats why I said I would be using them together when it matures. They are both very different in their approach. Most of my stuffs would still be from Scoop.

PS : As someone migrated from Chocolatey, I have zero respect for that product. Outdated apps, because updates depends on the maintainers whims and repeated checksum failures. winget using a github repository is already a plus.

**Comment by sinloss** [comment]
> We should add a Scoop manifest to WinGet Repo. So people can easily migrate to Scoop once they discover it's already years ahead.

Just like people are saying that the only use of the `Microsoft Edge` (*I mean the old version, the new chromium one is awesome!*) is to download `Chrome`. The `WinGet` would play the same role well.

**Comment by mxrss2** [comment]
https://www.theverge.com/2020/5/28/21272964/microsoft-winget-windows-package-manager-appget-copied

**Comment by lukesampson** [comment]
@mxrss2 except this time round it's even easier for Microsoft because we open source everything now?

**Comment by Naomi010Sentzke** [comment]
@mxrss2 Isnt AppGet written in C#, and winget in C++ ?

**Comment by Restia666Ashdoll** [comment]
@Naomi010Sentzke Read his blog, not the verge article. He didnt say that Microsoft copied his code, but his framework and his ideas
https://medium.com/@keivan/the-day-appget-died-e9a5c96c8b22
Here is the appget firefox manifest
![image](https://user-images.githubusercontent.com/56309157/83330663-48f13d00-a2ae-11ea-8234-b8afcb0956ac.png)
And the winget one
![image](https://user-images.githubusercontent.com/56309157/83330682-7807ae80-a2ae-11ea-8b7e-e09aa0ae37ba.png)
Its kind of like someone used Scoop for a month and made a package manager based on what he learned. winget is definitely inspired by appget, they didnt copy any code though.

**Comment by Airkro** [comment]
Maybe `winget` can solve this problem: https://github.com/lukesampson/scoop/issues/3691

I prefer using the package manager install `apps with self-updaters (chrome, vscode, etc.)` once, silently, when I buy a new computer. Then using their self-updater without breaking their manifests (scoop can't do that for now).

And use `scoop` for apps can't self-update.

**Comment by mxrss2** [comment]
@Restia666Ashdoll they gave him a nod for the attribution.

**Comment by GrooveCS** [comment]
I vote to keep [Scoop](https://www.slant.co/topics/1843/~best-windows-package-managers#2) until [WinGet](https://github.com/microsoft/winget-cli) is mature, and Scoop is redundant. [Chocolatey](https://chocolatey.org/) in the past and severe overhead.

**Comment by keentext** [comment]
> I vote to keep [Scoop](https://www.slant.co/topics/1843/~best-windows-package-managers#2) until [WinGet](https://github.com/microsoft/winget-cli) is mature, and Scoop is redundant. [Chocolatey](https://chocolatey.org/) in the past and severe overhead.

Winget is creating yet more fragmentation in windows, and the problem gets twice worse with win 11. https://github.com/microsoft/winget-cli/issues/1262

**Comment by keentext** [comment]
but i don't think that scoop users have to worry much, so long as we can use scoop to easily install python and we prevent all the garbage that comes from using windows store, and we keep everything portable, we'll always be an example of the superior quality of a community of users who care. https://github.com/microsoft/winget-cli/issues/1745

**Comment by EqualDust** [comment]
Let's all appreciate that scoop is great, and the community does not release broken packages: https://github.com/microsoft/winget-cli/issues/1750

**Comment by Luiz-Monad** [comment]
> > I vote to keep [Scoop](https://www.slant.co/topics/1843/~best-windows-package-managers#2) until [WinGet](https://github.com/microsoft/winget-cli) is mature, and Scoop is redundant. [Chocolatey](https://chocolatey.org/) in the past and severe overhead.
> 
> Winget is creating yet more fragmentation in windows, and the problem gets twice worse with win 11. [microsoft/winget-cli#1262](https://github.com/microsoft/winget-cli/issues/1262)

Fragmentation ? 

have you ever tried to tried _Dockerfile_ scripts for linux ? how do you update and install packages differe WILDLY.

With Windows, I can use Scoop and Chocolatey and WinGet and the WinStore, all of them, from the same shell command interface, thanks to OneGet magic. 

Windows has a package manager manager ! for when you need to install a package manager to manage your package manager. All of it from powershell scheduled task to update.

I wish there was something like "one-get" for linux, I never know if I need to :


Ubuntu | APT | sudo apt-get install <package>
-- | -- | --
Debian | APT | sudo apt-get install <package>
CentOS/RHEL | YUM | sudo yum install <package>
Fedora | DNF | sudo dnf install <package>
Arch Linux | Pacman | sudo pacman -S <package>
openSUSE | Zypper | sudo zypper install <package>
Slackware | pkgtools | sudo installpkg <package>
Gentoo | Portage | sudo emerge <package>
Void Linux | XBPS | sudo xbps-install -S <package>
Alpine Linux | APK | sudo apk add <package>
NixOS | Nix | nix-env -i <package>
Solus | eopkg | sudo eopkg install <package>
FreeBSD | pkg | sudo pkg install <package>
OpenBSD | pkg_add | sudo pkg_add <package>

"Windows is fragmented"

**Comment by polarathene** [comment]
> I wish there was something like "one-get" for linux, I never know if I need to

You can find [projects like this one](https://github.com/sxiii/linux-unified-packager) that should do the job? But are you distro-hopping that frequently that you really need this? Realistically you're not extensively using all of these package managers.

- If you're in a sysadmin / devops role and this is a concern, you likely already use an abstracting like Salt or Ansible and don't worry about this. If you're working with a package manager directly for some reason and you're not confident, you may have a [resource like this](https://distrowatch.com/dwres.php?resource=package-management) as a cheatsheet to reference, or could easily find one.
- If you're a user, you have a GUI app store like Discover which leverages [PackageKit backends](https://en.wikipedia.org/wiki/PackageKit#Back-ends) to handle this so you don't need to. If you write software where your app needs this support, you could do the same.
- If you're a developer, you'll tend to have a primary system and only bother with one package manager, you're not distro hopping. If the software you work on needs to be packaged, you have options like [GoReleaser / nFPM](https://goreleaser.com/customization/nfpm/) that should meet all your needs. You can then distribute via something like CloudSmith and do your CI.
- BSD OS aren't Linux btw.

---

> have you ever tried to tried `Dockerfile` scripts for linux? how do you update and install packages differ WILDLY.

How often are you doing that?

- I use Docker quite a bit and it's rare that you need to modify the image to that extent if you're doing things correctly.
- Your own projects rarely need to support multiple base images, usually it's Debian + Alpine / Distroless and this rarely changes afterwards.
- If it's a legitimate concern for you, such as modifying third-party images, you can probably just use `nix` for consistency / comfort.

---

> thanks to OneGet magic

Did you [check the project README](https://github.com/OneGet/oneget#announcement) when you posted? They no longer actively develop the project further. You're direct to [`AnyPackage` project](https://github.com/anypackage/anypackage) instead now.

It'll work for now perhaps, but the 95 unresolved issues and lack of interest to continue development by refusing PRs doesn't help. Most of the commit history for a while is just updating the CI config.

> "Windows is fragmented"

I don't care about the statement much. Just a Linux user that's coming across the different options for Windows along with these meta / wrapper projects to unify them doesn't really make it seem any different 🤷‍♂️

**Comment by NatoBoram** [comment]
Isn't this getting widely off-topic?
