### ISSUE TITLE
Shims don't work in WSL

### ISSUE THREAD

**Issue by daniel-liuzzi** [ScoopInstaller/Scoop#4035]
I've been playing around with the new WSL 2 in Windows 10, version 2004, and noticed the shim for Visual Studio Code (and probably others) don't seem to work from a Linux shell. According to [Run in Windows Subsystem for Linux](https://code.visualstudio.com/remote-tutorials/wsl/run-in-wsl), running `code .` from within WSL should first install the VS Code Server, then fire up VS Code, and finally connect to the server:

![launch-code](https://code.visualstudio.com/assets/remote-tutorials/wsl/launch-code.png)

But when I try that I get an error instead:

![wsl](https://user-images.githubusercontent.com/143884/84929193-c818aa80-b0cf-11ea-9a88-5bd310c66f45.png)

It's worth noting that the error only happens in a Linux directory such as `~`; Windows directories such as `/mnt/c/...` work fine.

**Comment by cwm12138** [comment]
The same problem in scoop-extra repo [#2581](https://github.com/lukesampson/scoop-extras/issues/2581)

**Comment by david-bakin** [comment]
For vscode the shim fix [here at #2581](https://github.com/lukesampson/scoop-extras/issues/2581#issuecomment-623868510) works.  But you have to reapply it every time vscode updates.  A proper solution by scoop when installing is desirable.  I make a [small suggestion here](https://github.com/lukesampson/scoop-extras/issues/2581#issuecomment-632439327).

**Comment by BatmanAoD** [comment]
In general, I would say that `scoop`'s auto-generated `sh` shims probably shouldn't be expected to work in WSL. But in the case of VSCode, the application installer _already provides_ a working shim. I've opened a PR here to suggest that Scoop simply expose that script as a symlink: https://github.com/lukesampson/scoop/issues/4413

That said, `scoop`'s shims would probably interact better with WSL simply by using powershell rather than `cmd`. I found this when trying to write my own shim for gVim: https://github.com/microsoft/WSL/issues/5811

For reference, here's the shim I ended up with: https://github.com/BatmanAoD/public-config/blob/master/OS_specific/Windows/wsl_host_gvim

**Comment by BatmanAoD** [comment]
Also related, I wrote this to deal with the lack of handling in `cmd.exe` for WSL paths. `abspath` here is essentially just `wslpath -aw`.

```
    wsl_batch () { 
        args=();
        for a in "$@"; do
            # For now, we don't preserve the working directory (see below), so
            # any existing file arguments are transformed to their absolute
            # paths. Unfortunately, this won't happen for new files (b/c they
            # don't exist yet).
            if [[ -e "$a" || ("$a" = */* && "$a" != *=*/* ) ]]; then
                args+=("$(abspath "$a")");
            else
                args+=("$a");
            fi;
        done;
        # `cmd.exe` prints an error message and changes the working directory
        # if started in a WSL directory.
        (
            # WSL_PWD="$(abspath "$PWD")";
            \cd /mnt/c;
            # TODO `pushd` only mounts the directory temporarily; additionally,
            # the mount seems that the mount can become corrupted somehow.
            # So for now, simply don't even try to preserve the working directory.
            # cmd.exe /c pushd "$WSL_PWD" "&&" "${args[@]}"
            cmd.exe /c "${args[@]}"
        )
    }
```
