### ISSUE TITLE
Scoop installation errors

### ISSUE THREAD

**Issue by MantisGalaxy** [ScoopInstaller/Scoop#4045]
So, I was trying to install Scoop and my Wi-Fi just went off, Scoop's installation stopped and gave an error. When I got it back up and tried to reinstall scoop, it kept saying it was already installed. So, I went to the local folder to check if scoop was installed but it wasn't. What do I do now?

**Comment by avandesa** [comment]
Hi there, I had a similar issue after a windows fresh start. See if there's a `.scoop` folder in your user directory. If so, try deleting it and reinstalling again. This is what worked for me.

**Comment by Sgt-Nukem** [comment]
I had a different issue but similar results when I had to reset (not reinstall) my Windows installation: I wanted to try out scoop instead of chocolatey and the installer always said "Scoop is already installed. Run 'scoop update' to get the latest version." while 'scoop update' just said "scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program."

Turns out I played around with scoop years ago and thus the 'scoop' folder was still intact in my Windows installation (reset will keep personal folders!) but the command was not registered in %PATH% anymore I guess.

Thanks to @avandesa I could quickly resolve it, but it was a bad first time user experience (as I didn't remember using scoop years ago at all).

### **Suggestion:**
- **a) EITHER let the installer not just check for the existence of the 'scoop' folder but also if it has been added to %PATH%**
- **b) OR don't bail out when 'scoop' is an existing folder and just do your usual installation anytime the installation command ist copy-pasted to PowerShell.**

**Comment by rashil2000** [comment]
#4005
