### ISSUE TITLE
Question about "Open With" and scoop installed apps.

### ISSUE THREAD

**Issue by ephemerr** [ScoopInstaller/Scoop#4153]
Hello! 

scoop is great!

But app I install with scoop do not appear in "Open With" dialogue. 

Is there a way to put them there?

**Comment by devdanzin** [comment]
You can add at least some of them manually by selecting (translated from another language) "Open with" -> "Choose another application" -> "More applications" ->  "Find another application in this PC". I was able to register scoop installed OpenShot to handle PNGs that way. But it only helps if you need at most a couple of apps there. 

It seems we could add applications automatically from PowerShell: https://superuser.com/a/1462320

**Comment by FriendlyNeighborhoodShane** [comment]
As @devdanzin stated above, you can simply add any program by path to the "open with" menu. However, there are some complications.

It is IMPERATIVE that you add the proper program path (`$HOME/scoop/apps/mpv/current/mpv.exe`), and not the shim path.
   - (If you do not go through the `current` shortcut and go through the actual version number, the link association will expire whenever you update the program.)
   - (Of course, this too does not work well with programs that have unstable executable pathing, like GIMP (`bin/gimp-2.10.exe`).)

If you add the shim path (`$HOME/scoop/shims/mpv.exe`), it will spell disaster. The shim will show up as an ugly iconless, nameless blob in the "Open With" menu. It will be impossible to tell between when you have multiple shims registered. The files too will forever be haunted by that icon. Sometimes the shim won't even close itself after launching the program.

What's more, if you add the shim for a program ONCE, Windows will not even let you let you add the proper path for it as an option anymore, presumably because it thinks that a program with the same basename is already registered and so there's no need to add the new path.

I added a few of those by mistake yesterday and almost pulled my hair out trying to undo it. I succeeded in the end, however only after what can be described best as a life-and-death tussle with manual registry editing.

(Maybe I should add this to the wiki?)

**Comment by Calinou** [comment]
> (Perhaps I should add this to the wiki?)

Please do :slightly_smiling_face:

**Comment by FriendlyNeighborhoodShane** [comment]
@Calinou @ephemerr

https://github.com/lukesampson/scoop/wiki/Open-With-Icons
