### ISSUE TITLE
Cannot update kitty: Can't shim 'kageant.exe': File doesn't exist.

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#4326]
> Updating 'kitty' (0.74.4.7 -> 0.74.4.9)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: bb1089|OK  |   5.7MiB/s|D:/scoop/cache/kitty#0.74.4.9#https_github.com_cyd01_KiTTY_releases_download_v0.74.4.9
_kitty-bin-0.74.4.9.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of kitty-bin-0.74.4.9.zip ... ok.
Uninstalling 'kitty' (0.74.4.7)
Removing shim for 'genpass'.
Removing shim for 'kageant'.
Removing shim for 'kitty'.
Removing shim for 'kittygen'.
Removing shim for 'klink'.
Removing shim for 'kscp'.
Removing shim for 'ksftp'.
Unlinking D:\scoop\apps\kitty\current
Installing 'kitty' (0.74.4.9) [64bit]
Loading kitty-bin-0.74.4.9.zip from cache.
Extracting kitty-bin-0.74.4.9.zip ... done.
Running pre-install script...
Linking D:\scoop\apps\kitty\current => D:\scoop\apps\kitty\0.74.4.9
Creating shim for 'genpass'.
Creating shim for 'kageant'.
Can't shim 'kageant.exe': File doesn't exist.

**Comment by quantuumsnot** [comment]
Next time test the things because it's broken.
After `scoop reset kitty` failed, doing successful `scoop uninstall kitty` followed by failed `scoop install kitty` the ssh keys are GONE!!!

**Comment by quantuumsnot** [comment]
Here, read it again:

**KEYS ARE GONE!!!**

**Comment by arielsalvo** [comment]
@quantuumsnot

It seems the package definition is auto-updated. I don't know how that works myself but there is only so much that can be tested in that regard with the amount of packages handled by scoop.

It seems that the release from the upstream maintainer is missing the file kageant.exe since version v0.74.4.9 (read all about it [here](https://github.com/cyd01/KiTTY/releases/tag/v0.74.4.9)).

Anyway, no need to despair... There are a couple of things you can do:
1. Just revert to a previous version until the whole thing is fixed:
> scoop uninstall kitty
> scoop install kitty@0.74.4.8
> scoop hold kitty

2. If scoop's package is fixed and kageant.exe is still missing:
> kitty.exe -runagent

Hope that helps!

Regards!
   --Ariel

**Comment by quantuumsnot** [comment]
Already fixed it because we have backups. Default behavior of scoop is to save everything in `persist` directory when the reinstall moment occurs. For security reasons we allow only the corresponding apps to access only their persist sub-dirs and if they're missing like `kageant.exe` that sub-dir is backed up then removed ... Yeah, OUR fault to believe that scoop app installations are STABLE during update. Our suggestion is that if `scoop` is still here to offer some Linux-style package management then just test app updates before making them public

**Comment by r15ch13** [comment]
@quantuumsnot Scoop does not save everything in the `persist` on reinstall. The `SshHostKeys` is created in the `persist` directory and symlinked back into the program directory so that the files are safe from being deleted on reinstall/uninstall actions.
`SshHostKeys` was added with https://github.com/lukesampson/scoop-extras/pull/3864 12 months ago.
