### ISSUE TITLE
Scoop stops after update error

### ISSUE THREAD

**Issue by gustavo-nramires** [ScoopInstaller/Scoop#4433]
When I update multiple applications using

`scoop update *`

I get an error sometimes such as **'The remote server returned an error: (404) Not Found'.** and also **'ERROR Hash check failed!'**. All other updates then fail as well.

https://github.com/lukesampson/scoop/blob/092005046454d94d141d5c68fdbdb4c4a1229ae9/lib/install.ps1

In lib/install.ps1 lines 379, 389 (function dl)
The exception throws an error. Wouldn't it be best to just print an error message?

in lib/install.ps1 line 111 (function dl_with_cache)
The function do_dl throws the error that is unhandled with try catch. It could be possible to pass it further via try and catch.

https://github.com/lukesampson/scoop/blob/092005046454d94d141d5c68fdbdb4c4a1229ae9/libexec/scoop-update.ps1

in libexec/scoop-update.ps1 line 209, dl_with_cache is called that may give an uncaught error. This stalls multiple updates (that didn't have error).

Suggestion: Simply print error message in lib/install.ps1 lines 379, 389 (dl as well as in dl_with_cache_aria2 functions)

Thanks

**Comment by Ugenx** [comment]
+1 - just ran into this myself with a blocked download of an app I had installed prior to the block being put in place. I want to keep the app but I can't run update * because it errors out on one of the first entries. Temporary workaround has been to remove the offending app folder from scoop\apps, running update * and then restoring the app folder to its original location.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4135
