### ISSUE TITLE
rootPath is not created sometimes

### ISSUE THREAD

**Issue by maphew** [ScoopInstaller/Scoop#4628]
## Bug Report

initially discussed at https://github.com/ScoopInstaller/Scoop/discussions/4622

#### Current Behavior

```
scoop config rootPath C:\apps\geo
scoop install $appname
```
results in _"Get-ChildItem : Cannot find path 'C:\apps\geo\shims' because it does not exist."_

#### Expected Behavior

The defined rootPath folder will be created if it doesn't exist.

### System details

**Windows version:** Microsoft Windows [Version 10.0.19042.1415]

**OS architecture:**  64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-01-06T13:32:15.7555330-07:00",
    "cachePath":  "\\\\envgeoserver\\share\\GIS-Software\\scoop\\cache",
    "rootPath":  "c:\\apps\\geo"
}

```

**Comment by maphew** [comment]
Here's the complete script and it's output as it stands now
https://gist.github.com/maphew/8b9ad8ba64c7121cd7502bfcef8ce025

**Comment by niheaven** [comment]
Found the problem...

Since you install scoop in the beginning, scoop create `shims` and `buckets` in that step, and then you change `rootPath` to another directory which don't have `shims` and `buckets` sub-dir.

Are you sure you want scoop installed in another place? For your usage, you'd better set EnvVars (by `$Env:xxx = xxx`) before your installation, e.g., `SCOOP`, `SCOOP_GLOBAL` and `SCOOP_CACHE`, and then set them accordingly in config file.

**Comment by maphew** [comment]
Ah that makes sense. I didn't know about the env vars, I'll do that. Thank
you.

**Comment by chawyehsu** [comment]
`rootPath`, `cachePath`, `globalPath` were introduced to repalce `$env:SCOOP`, `$env:SCOOP_CACHE` and `$en:SCOOP_GLOBAL` envs. There are used in the new standalone installer, you can try it at https://github.com/ScoopInstaller/Install. Once the installation finished, `rootPath` should not be changed.

Follow the readme document and you will be able to install Scoop into a specified location. The standalone installer is still a WIP, it's already stable though.

**Comment by maphew** [comment]
The standalone installer process using command line parameters for rootPath and cache worked perfectly, thank you.
