### ISSUE TITLE
[Bug] Cannot open file via the file opened history in the context menu of Icon in the taskbar.

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Scoop#4865]
#### Current Behavior
I cannot open file via the file opened history in the context menu of Icon( typora, sumatraPDF at least) in the taskbar. But when I install typora and sumatraPDF via its setup programme, I can open via file.

#### Expected Behavior
open file via file opened history in the menu of Icon in the taskbar.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.2

**Comment by rashil2000** [comment]
I can't reproduce this with the programs I have installed via Scoop. File history works for me.

![image](https://user-images.githubusercontent.com/46838874/162811653-56b87120-ecb9-4955-8b9c-4946b416b42d.png)

![image](https://user-images.githubusercontent.com/46838874/162811735-9766a469-b541-4583-8b9c-0fef479e7492.png)


You need to register .md files with Typora for this to happen.

**Comment by NamelessUzer** [comment]
> I can't reproduce this with the programs I have installed via Scoop. File history works for me.
> 
> ![image](https://user-images.githubusercontent.com/46838874/162811653-56b87120-ecb9-4955-8b9c-4946b416b42d.png)
> 
> ![image](https://user-images.githubusercontent.com/46838874/162811735-9766a469-b541-4583-8b9c-0fef479e7492.png)
> 
> You need to register .md files to open with Typora for this to happen.

I can also find this file history list. But I cannot open the items in the list. every time I tried to open it, I am told "the item may has been moved, renamed or delete. Do you want to remove it from the list?".
I am sure I have register .pdf to sumatrapdf(open a pdf and select "always use this application to open it"). and I have installed/uninstalled sumatrapdf several times.
only the sumatrapdf install by scoop cannot open item in file history list.

**Comment by rashil2000** [comment]
I just installed SumatraPDF, and I'm able to open the PDF through the file history list correctly.

**Comment by NamelessUzer** [comment]
> 

I have to install SumatraPDF via its installer. and It works very well. Should we reopen this issue?

**Comment by rashil2000** [comment]
I would have to recognize and reproduce this as a bug first. @issaclin32 any thoughts?

**Comment by issaclin32** [comment]
I repoduced the problem by:
installing `sumatra@3.3.2`, uninstall it, and install `sumatra@3.3.3`.

It looks like Windows somehow avoids using symlinks for registering the app in history/file associations, etc. 
That is, Windows registers `(SCOOP_DIRECTORY)\apps\sumatrapdf\3.3.2\SumatraPDF.exe` instead of  `(SCOOP_DIRECTORY)\apps\sumatrapdf\current\SumatraPDF.exe`, which is causing the problem to repeat between updates.

We can probably solve by using the approach in https://github.com/ScoopInstaller/Extras/pull/7554, but that would be a lot of work, considering how many packages we need to modify.

There a some similar problems:
https://github.com/ScoopInstaller/Extras/issues/7025
https://github.com/ScoopInstaller/Extras/issues/2616

**Comment by santagoy** [comment]
The bug still persists. I still can't render sumatrapdf as my main installer through Scoop.
