### ISSUE TITLE
[Bug] Scoop checking ~/scoop instead of custom dir after update

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Scoop#4918]
#### Current Behavior

Ran 'scoop update *', the app was updated to v0.2.0, tried running 'scoop list' and it returned 'no apps installed'.

Tried other commands and noticed hints to it looking in my Users dir.

Checked environment variables and noticed SCOOP was completely vanished.

Luckily, the app is otherwise very stable, so manually adding it again and pointing it to the desired dir fixed everything.

#### Expected Behavior

Updating Scoop to a new version should not result in the environment variables getting erased.

#### Additional context/output

I'm using a custom dir for my Scoop installation.

#### Possible Solution

Finding the technical cause to the environment variable getting erased.

### System details

**Windows version:** 11 - 22000.613

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

**Additional software:** 

Other tools like MSYS2 always show warnings cause I've a Kaspersky security product, though I've never ran into any issues while running that shell or anything else - no conflicts detected while updating, and everything seemed normal till I was attempting my next command as described above.

#### Scoop Configuration

```json
//# Your configuration here

{
  "rootPath": "F:\\Backup\\Scoop",
  "lastUpdate": "2022-05-12T19:24:06.4048137+02:00",
  "aria2-warning-enabled": false,
  "MSIEXTRACT_USE_LESSMSI": true,
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}

```

**Comment by rashil2000** [comment]
That's strange, I don't think the codebase has any code to erase/reset the SCOOP variable - it only reads it if found. Something else must be at play...

**Comment by Vedabahu** [comment]
## Bug Report

#### Current Behavior
Instead of looking in the custom directory of scoop, it is looking in `C:\Users\Users\Scoop\` and giving me error. I tried removing scoop and reinstalling it. Showing the same problem.
`scoop help` Output:
![image](https://user-images.githubusercontent.com/79869936/168145669-82588a6b-b588-4a5d-978a-de32d6c4d603.png)


#### Expected Behavior

Look for buckets and all installs directly in the desired directory as in scoop's `config.json` file.

### System details

**Windows version:** 7

**OS architecture:** 64bit

**PowerShell version:** 
```powershell
PS D:\Vedabahu\Scoop> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      3
```


#### Scoop Configuration

```json
{
  "lastUpdate": "2022-05-12T23:26:56.2305288+05:30",
  "rootPath": "D:\\Vedabahu\\Scoop\\Scoop",
  "globalPath": "D:\\Vedabahu\\Scoop\\ScoopGlobal",
  "cachePath": "D:\\Vedabahu\\Scoop\\ScoopCache",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-split": 16,
  "aria2-max-connection-per-server": 16,
  "aria2-warning-enabled": false,
  "MSIEXTRACT_USE_LESSMSI": true,
  "aria2-enabled": true
}
```

**System Details**:
Windows 7 Ultimate v6.1 SP1
Build 7601

**Comment by Vedabahu** [comment]
I found a workaround. If we install without the Environment Variables using scoop installer, scoop will later look for the `~\scoop` directory. It wont check the config file for root dir, cache dir and global dir.

If i set the environment variables, it works properly.

**Comment by bejelentkezni** [comment]
Not much of a workaround when you've already got several gigabytes installed. It would be nice if such breaking changes were announced in advance.

**Comment by sprgchma** [comment]
There is bug in the lib/core.ps1: the code uses the configuration before loading it:

- here the code uses configuration to get `$scoopdir` (line 1113): https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1113

- but loads `$scoopConfig` after the using! (line 1136): https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1136

The error gone when I moved these lines https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1125-L1136 directly after the `Optimize-SecurityProtocol` invocation at https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1110

**Comment by rashil2000** [comment]
The source of error might be something else, because the code you mentioned hasn't been touched in 3 years...

![image](https://user-images.githubusercontent.com/46838874/168655417-62fe246a-eada-462b-a94e-bd3a85e4921a.png)

**Comment by sprgchma** [comment]
@rashil2000 I think the culprit is this commit https://github.com/ScoopInstaller/Scoop/commit/6296822f1fa203c73552bd1f94f06686f5bbb562. 

Step-by-step

- The error manifests itself in a situation when the scoop dir has non-default value given by the `rootDir` is the configuration file. It is true for my case and for the case of @RavenMacDaddy 
- Judging from the name of commit ("Load libs only once") the core.ps1 was loaded at least twice originally
- And during the second load the `$scoopConfig` was defined by the first one - so  `$scoopdir` and other variables got their value from the config!
- It seems fixing the "multiple-loads" bug reveals this particular "use-config-before-load" incorrect behaviour.

**Comment by rashil2000** [comment]
Wow, you're right. Nice observation!


> The error gone when I moved these lines https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1125-L1136 directly after the `Optimize-SecurityProtocol` invocation at https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1110

Can you make a PR for this?
