### ISSUE TITLE
[Bug] Command option error, `-s, --skip`

### ISSUE THREAD

**Issue by HUMORCE** [ScoopInstaller/Scoop#4927]
#### Current Behavior

Cannot skip hash validation with command option `-s` when installing/updating apps.

#### Expected Behavior

SCOOP installs/updates the specified apps, and skip the hash validation

#### Additional context/output

```powershell
❯ scoop install app -s
scoop.ps1: C:\Users\HUMOR\scoop\shims\scoop.ps1:3
Line |
   3 |  … n.ExpectingInput) { $input | & $path  @args } else { & $path  @args }
     |                                                                  ~~~~~
     | Missing an argument for parameter 'SubCommand'. Specify a parameter of type
     | 'System.Object' and try again.

❯ scoop install app --skip
Couldn't find manifest for 'app'.
```

`--skip` works fine, but `-s` does not, and other short options works.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** windows powershell 5.1.22000.653 / powershell core 7.2.3

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    ...
    "aria2-enabled": false,
    "MSIEXTRACT_USE_LESSMSI": true,
    "proxy": "none"
}
```

**Comment by lewis-yeung** [comment]
That's caused by a rule in PowerShell: If we use a hyphen plus the prefix of a defined parameter name in command line and it's not ambiguous, PowerShell respects it as the corresponding parameter name. In this case, `-s` is interpreted as a "shorthand" of `-SubCommand`, and we will get the same error by `scoop install app -sub`, `scoop install app -subc`, etc.

https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/bin/scoop.ps1#L2

**Comment by rashil2000** [comment]
Relevant commit: https://github.com/ScoopInstaller/Scoop/commit/6296822f1fa203c73552bd1f94f06686f5bbb562#diff-213b1f5a9e808d219e5e8f4d95bb6526eb5bdd61bae792958abafd876bcb47c8

**Comment by lewis-yeung** [comment]
Obviously `scoop install app '-s'` works correctly because `'-s'` is directly passed as s string. However `scoop '-v'` doesn't work as `scoop -v` or `scoop --version` but shows an error:

```
scoop: '-v' isn't a scoop command. See 'scoop help'.
```

So we should not use a named parameter but need to convert arguments to string objects in `bin/scoop.ps1` before passing them to a specific command.

```diff
@@ -1,6 +1,8 @@
 #Requires -Version 5
-param($SubCommand)
-
+if ($Args.Count -gt 0) {
+    [string]$SubCommand = $Args[0]
+    [string[]]$arguments = $Args | Select-Object -Skip 1
+}
 Set-StrictMode -Off

 . "$PSScriptRoot\..\lib\core.ps1"
@@ -15,14 +17,10 @@ Get-ChildItem Function: | Where-Object -Property Name -In -Value $aliases | ForE
 }

 switch ($SubCommand) {
-    ({ $SubCommand -in @($null, '--help', '/?') }) {
-        if (!$SubCommand -and $Args -eq '-v') {
-            $SubCommand = '--version'
-        } else {
-            exec 'help'
-        }
+    ({ $SubCommand -in @($null, '-h', '--help', '/?') }) {
+        exec 'help'
     }
-    ({ $SubCommand -eq '--version' }) {
+    ({ $SubCommand -in @('-v', '--version') }) {
         Write-Host 'Current Scoop version:'
         if ((Test-CommandAvailable git) -and (Test-Path "$PSScriptRoot\..\.git") -and (get_config SCOOP_BRANCH 'master') -ne 'master') {
             Invoke-Expression "git -C '$PSScriptRoot\..' --no-pager log --oneline HEAD -n 1"
@@ -43,10 +41,10 @@ switch ($SubCommand) {
         }
     }
     ({ $SubCommand -in (commands) }) {
-        if ($Args -in @('-h', '--help', '/?')) {
+        if ($arguments.Count -gt 0 -and $arguments[0] -in @('-h', '--help', '/?')) {
             exec 'help' @($SubCommand)
         } else {
-            exec $SubCommand $Args
+            exec $SubCommand $arguments
         }
     }
     default {
```

Then everything works.
