### ISSUE TITLE
[Bug] Scoop update error

### ISSUE THREAD

**Issue by nirgranth** [ScoopInstaller/Scoop#6082]
```
scoop update
Updating Scoop...
 * be56faf29016 chore(release): Bump to version 0.5.1 (#6057)            9 days ago
 * 69edc6dc54ff chore(chglog): Update CHANGELOG for v0.5.1 (#6058)       11 days ago
 * 0138dc426657 fix(scoop-alias): Pass options correctly (#6003)         11 days ago
 * 1c271f5b90f2 fix(scoop-virustotal): Adjust `json_path` parameters t.. 2 weeks ago
 * a76884af1904 fix(install): Fix parsing error when installing multip.. 2 weeks ago
 * 7cc4faea1d0f fix(bucket): Implement error handling for failed bucke.. 3 weeks ago
 * 83f25a4673c2 fix(install): Expand env_set items (#6050)               3 weeks ago
 * 42af27d16c65 fix(sqlite): Fix compatibility with Windows PowerShell.. 3 weeks ago
Updating Buckets...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Invoke-GitLog:
Line |
  12 |  … nvoke-GitLog -Path $bucketLoc -Name $name -CommitHash $previousCommit
     |                                                          ~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'CommitHash' because it is an empty string.
     
```

**Comment by HUMORCE** [comment]
Caused by broken bucket(s.

1. Check added buckets: `scoop bucket list`
2. Remove broken bucket you think: `scoop bucket rm BUCKET_NAME`
3. Re-add bucket: `scoop bucket add BUCKET_NAME`, for 3rd party bucket: `scoop bucket add BUCKET_NAME REPO_URL`

**Comment by HUMORCE** [comment]
> How can one confirm which bucket is broken?

Many factors can damage a bucket, 

for git bucket: run `git pull` on the bucket dir, it's fine when pulls latest.
for dir bucket: possible permissions or manifest issues when the directory structure is correct

**Comment by amaretto-sh** [comment]
After removing and re-adding all of my buckets and doing other type of things such as 
`scoop install 7zip git openssh` (core functionality that Scoop relies on)
resetting scoop 
`scoop cleanup * && scoop update`
and at last
`scoop status` and `scoop checkup` (this one is useful)

I realised I was just doing all of this for nothing because 1. I wasn't in the right path (make fun of me, its deserved), and **2. I wasn't running as admin**. Windows doesn't automatically give you admin rights. Maybe this one issue is not about sudo specifically, but I had the same output error so I still share.

**Run your terminal as admin, it might fix this problem.**
